apiVersion: apps/v1
kind: Deployment
metadata:
  name: movies
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
        - name: movies
          image: karthikswarnkar/movies
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: movies-service
spec:
  selector:
    app: movies
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Use NodePort if LoadBalancer isn't available
